FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git && \
    rm -rf /var/lib/apt/lists/*

COPY . /app/

ENV SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0

RUN pip install --no-cache-dir ".[grpc]" && \
    pip install --no-cache-dir grpcio-health-checking grpcio-reflection

EXPOSE 6572

ENTRYPOINT ["feast"]
CMD ["serve_registry", "--rest-api"]
