FROM registry.access.redhat.com/ubi9/python-312-minimal:1

USER 0

RUN microdnf install -y npm git gcc libpq-devel python3.12-devel && microdnf clean all
RUN npm install -g yarn yalc && rm -rf .npm

USER 1001

COPY --chown=1001:0 .git /opt/app-root/src/.git
COPY --chown=1001:0 pyproject.toml README.md Makefile /opt/app-root/src/
COPY --chown=1001:0 protos /opt/app-root/src/protos
COPY --chown=1001:0 ui /opt/app-root/src/ui
COPY --chown=1001:0 sdk/python /opt/app-root/src/sdk/python

WORKDIR /opt/app-root/src/ui
RUN npm install && \
    npm run build:lib-dev && \
    rm -rf node_modules && \
    npm cache clean --force

WORKDIR /opt/app-root/src/sdk/python/feast/ui
RUN yalc add @feast-dev/feast-ui && \
    git diff package.json && \
    yarn install && \
    npm run build --omit=dev && \
    rm -rf node_modules && \
    npm cache clean --force && \
    yarn cache clean --all

WORKDIR /opt/app-root/src

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
ENV UV_CACHE_DIR=/tmp/uv-cache

RUN uv pip install -e ".[minimal]"

RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json

ENV DATACATALOG_ENABLED=true
ENV DATACATALOG_SSAR_ENABLED=true
