FROM python:3.12-slim

RUN apt-get update && apt-get install -y git gcc libpq-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY .git /app/.git
COPY pyproject.toml README.md Makefile /app/
COPY protos /app/protos
COPY sdk/python /app/sdk/python

RUN pip install --no-cache-dir -e ".[minimal]"

ENV DATACATALOG_ENABLED=true
ENV DATACATALOG_SSAR_ENABLED=false

USER 1001
